#!/bin/bash

# Prompt the user to enter the remote IP and port
read -p "Enter the remote IP: " REMOTE_IP
read -p "Enter the SSH port (default is 22): " SSH_PORT
SSH_PORT=${SSH_PORT:-22}  # Use port 22 by default if no port is specified

# Add your SSH key to the remote host
ssh-copy-id -p $SSH_PORT root@$REMOTE_IP

# Download the ovztransfer.sh script and save it as ovztransfer.sh
wget -O ovztransfer.sh "https://src.openvz.org/projects/OVZL/repos/ovztransfer/raw/ovztransfer.sh?at=refs%2Fheads%2Fmaster"

# Assign execute permissions to the script
chmod +x ovztransfer.sh

# Check if screen is installed, and install if not
if ! command -v screen &> /dev/null; then
    if command -v apt-get &> /dev/null; then
        echo "screen is not installed. Installing it..."
        sudo apt-get update
        sudo apt-get install screen -y
    elif command -v yum &> /dev/null; then
        echo "screen is not installed. Installing it..."
        sudo yum update
        sudo yum install screen -y
    else
        echo "Unable to install screen. Please install it manually and run the script again."
        exit 1
    fi
fi

# List VMs and exclude the header line
CTID_LIST=$(vzlist -a | awk '{print $1}' | grep -v CTID)

# Start a screen session
screen -dmS vm_management

# Run the VM management script inside the screen session
screen -S vm_management -X stuff "
for CTID in $CTID_LIST; do
    echo 'Managing VM $CTID'
    
    vzctl stop
